
//Number of projects in this VS solution:  1


// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;




[assembly: AssemblyVersion("7.9.2020.1185")]
[assembly: AssemblyFileVersion("7.9.2020.1185")]
