
//Number of projects in this VS solution:  1


// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;




[assembly: AssemblyVersion("5.9.2020.880")]
[assembly: AssemblyFileVersion("5.9.2020.880")]
